import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu-Clone: for demonstration only</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        Lets hope git is working now!
      </h1>
      

      <footer >

      </footer>
    </div>
  )
}
